packages:
  - .

allowBuilds:
  "@developer-overheid-nl/adr-rulesets": true
  '@developer-overheid-nl/adr-rulesets@https://codeload.github.com/developer-overheid-nl/adr-rulesets/tar.gz/da1327dfcc83ed130b1fe5aaa282b7bfba537aee': true
  '@scarf/scarf': false
  esbuild: true

overrides:
  brace-expansion@<1.1.18: 1.1.18
  fast-uri@<3.1.8: 3.1.8
  'fast-xml-parser@>=5.9.3 <5.10.1': 5.10.1
  fast-xml-builder@<=1.1.6: 1.2.0
  'js-yaml@>=4.0.0 <4.3.2': 4.3.2
  lodash@<=4.17.23: 4.18.1
  yaml@>=1.0.0 <1.10.3: 2.9.0
